### ISSUE TITLE
Redis is not been used?

### ISSUE THREAD

**Issue by ShlomiPorush** [umuterturk/email-verifier#11]
Thanks for the docker image 🎉- i was able to set it up quickly.
I noticed that Redis doesn't actually store any data (I know it's only for caching)
opened redis in RedisInsight and I don't see any values ​​being stored.

Is this okay?

My docker compose 

```
services:
  email-validator:
    image: umutert/emailvalidator:latest
    container_name: EmailValidator
    security_opt:
      - no-new-privileges:true
    hostname: EmailValidator
    restart: unless-stopped
    networks:
      - traefik
      - emailvalidator
    environment:
      - PROMETHEUS_ENABLED=false
      - REDIS_URL=redis://redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emailvalidator.entrypoints=https"
      - "traefik.http.routers.emailvalidator.rule=Host(`emailvalidator.${DOMAIN}`)"
      - "traefik.http.routers.emailvalidator.tls=true"
      - "traefik.http.routers.emailvalidator.service=emailvalidator"
      - "traefik.http.routers.emailvalidator.middlewares=default-headers@file"
      - "traefik.http.services.emailvalidator.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:alpine
    networks:
      - emailvalidator
    volumes:
      - redis-temp:/data
    command: redis-server --appendonly yes

networks:
  traefik:
    external: true
  emailvalidator:
    external: true

volumes:
  redis-temp:
    external: true
```
